### ISSUE TITLE
ConfigMap example incorrect

### ISSUE THREAD

**Issue by pandalec** [owncloud/docs-ocis#320]
Hey!
Thanks for fixing the documentation for the [config map example](https://doc.owncloud.com/ocis/next/deployment/container/orchestration/tab-pages/generic-configs-tab-1.html) but it is incorrect:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-users
type: Opaque
data:
  # how to generate: create a UUIDv4
  # example generation command: `cat /proc/sys/kernel/random/uuid`
  # Only set to "1284d238-aa92-42ce-bdc4-0b0000009157" if you
  # migrate an existing oCIS installation from 2.0.0-rc.1 and earlier.
  storage-uuid: XXXXXXXXXXXXX
```

There"s no `type` for ConfigMaps, Secrets have types. It must be:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-users
data:
  # how to generate: create a UUIDv4
  # example generation command: `cat /proc/sys/kernel/random/uuid`
  # Only set to "1284d238-aa92-42ce-bdc4-0b0000009157" if you
  # migrate an existing oCIS installation from 2.0.0-rc.1 and earlier.
  storage-uuid: XXXXXXXXXXXXX
```

BR
panda
