### ISSUE TITLE
[5.0] Use env variable in yaml config files

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-ocis#765]
References: https://github.com/owncloud/ocis/pull/8339 (feat: use env variable in yaml config files)

We added the ability to use environment variables in yaml config files. This allows to use environment variables in the config files of the ocis services which will be replaced by the actual value of the environment variable at runtime.

Example:

```yaml
web:
  http:
    addr: ${SOME_HTTP_ADDR}
```
